"""The replay log a benchmark writes beside its rollup, for a replay.

`log.py` owns the format, the writer a benchmark uses, and a reader. `events.py`
holds the Manifold events a step carries. Nothing here touches the bridge - a replay
is never part of the stream the two sides exchange (ADR 0003).
"""

from __future__ import annotations

from manifold.replay.events import (
    Above,
    Behind,
    CenteredOn,
    Closed,
    EpisodeEnded,
    EpisodeStarted,
    Grasped,
    GripperAction,
    GripperCommanded,
    GripperFullyClosed,
    GripperHit,
    GripperTouching,
    InFrontOf,
    Inside,
    LeftOf,
    ManifoldEvent,
    ManifoldEventKind,
    Note,
    ObjectDisplaced,
    ObjectFact,
    ObjectLeftScene,
    ObjectOccurrence,
    ObjectTipped,
    On,
    Open,
    Outside,
    RelationFact,
    RightOf,
    Severity,
    Stacked,
    StackOrder,
    Touching,
    TurnedOn,
    Upright,
)
from manifold.replay.log import (
    REPLAY_LOG_DIR,
    REPLAY_LOG_SUFFIX,
    REPLAY_LOG_VERSION,
    CameraPinhole,
    Channel,
    ChannelKind,
    Mesh,
    Pose,
    ReplayFrameType,
    ReplayLog,
    ReplayLogWriter,
    ReplayStep,
    SceneBody,
    ScenePart,
    read_replay_log,
    replay_log_path,
)

__all__ = [
    "REPLAY_LOG_DIR",
    "REPLAY_LOG_SUFFIX",
    "REPLAY_LOG_VERSION",
    "Above",
    "Behind",
    "CameraPinhole",
    "CenteredOn",
    "Channel",
    "ChannelKind",
    "Closed",
    "EncodedImage",
    "EpisodeEnded",
    "EpisodeStarted",
    "Grasped",
    "GripperAction",
    "GripperCommanded",
    "GripperFullyClosed",
    "GripperHit",
    "GripperTouching",
    "InFrontOf",
    "Inside",
    "LeftOf",
    "ManifoldEvent",
    "ManifoldEventKind",
    "Mesh",
    "Note",
    "ObjectDisplaced",
    "ObjectFact",
    "ObjectLeftScene",
    "ObjectOccurrence",
    "ObjectTipped",
    "On",
    "Open",
    "Outside",
    "Pose",
    "RelationFact",
    "ReplayFrameType",
    "ReplayLog",
    "ReplayLogWriter",
    "ReplayStep",
    "RightOf",
    "SceneBody",
    "ScenePart",
    "Severity",
    "StackOrder",
    "Stacked",
    "Touching",
    "TurnedOn",
    "Upright",
    "read_replay_log",
    "replay_log_path",
]
